# action名称
name: Push Release

# 当代码合并到master分支的时候，执行下列脚本
on:
  push:
    branches: [ master ]

# 任务
jobs:
  # publish-npm任务
  publish-npm:
    # 在ubuntu最新版本的虚拟机执行
    runs-on: ubuntu-latest
    # 设置变量
    strategy:
      matrix:
        node-version: [ 10.15.0 ]
    steps:
      # 检查并切换到master分支
      - name: 检查master分支
        # 使用actions/checkout插件
        uses: actions/checkout@master

      # 安装node
      - name: 设置Node.js
        # 使用actions/setup-node插件
        uses: actions/setup-node@master
        with:
          # node版本
          node-version: ${{ matrix.node-version }}

      # 初始化缓存
      - name: 缓存
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/yarn.lock')}}

      - name: Install
        run: npm run bootstrap # 安装依赖

      - name: Build
        run: npm run dist # 打包

      # 读取当前版本号
      - name: 读取当前版本号
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          #根路径下的package.json
          path: ./package.json
          property: version

      # 发布NPM包
      - name: 发布NPM包
        # 执行发布代码
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish
        env:
          # 配置 npm access token 环境变量
          NPM_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}

      # 使用githubPage服务
      - name: 创建GitHub Pages Server
        id: create_pages
        uses: peaceiris/actions-gh-pages@v3
        env:
          # 配置github token （这个无需去github配置，默认存在的）
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish_dir: examples/element-ui # 部署打包后的 dist 目录
          github_token: ${{ secrets.deploy }} # secret 名
          commit_message: Update Github gh-pages # 部署时的 git 提交信息，根据自身需要填写即可

      # 创建GitHub Release
      - name: 创建GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          # 配置github token （这个无需去github配置，默认存在的）
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 标签名
          tag_name: v${{steps.version.outputs.value}}
          # release名
          release_name: v${{steps.version.outputs.value}}
          # 是否为草稿
          draft: false
          # 是否为预发布
          prerelease: false

      # 刷新缓存
      - name: 刷新缓存
        run: |
          curl https://purge.jsdelivr.net/npm/iemotion-pic@latest/dist/name.json
